# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-13 18:58
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zl955', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='b_desc',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='细节'),
        ),
        migrations.AddField(
            model_name='settings',
            name='description',
            field=models.CharField(default=1, help_text='请输入小于100字符的描述！', max_length=150, verbose_name='SEO-网站介绍词'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='explain',
            field=models.CharField(default=1, help_text='请输入小于100字符的描述！', max_length=150, verbose_name='网站声明'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='icons',
            field=models.ImageField(blank=True, null=True, upload_to='zl955/settings/', verbose_name='favicon图标'),
        ),
        migrations.AddField(
            model_name='settings',
            name='keywords',
            field=models.CharField(default=1, help_text='请输入小于100字符的描述！', max_length=150, verbose_name='SEO-网站关键词'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='logo_pic',
            field=models.ImageField(blank=True, null=True, upload_to='zl955/settings/', verbose_name='网站标题图片'),
        ),
        migrations.AddField(
            model_name='settings',
            name='m_desc',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='详细信息'),
        ),
        migrations.AddField(
            model_name='settings',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='settings',
            name='water_pic',
            field=models.ImageField(blank=True, null=True, upload_to='zl955/settings/', verbose_name='水印背景图片'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='name',
            field=models.CharField(help_text='请输入小于50字符的描述！', max_length=50, verbose_name='网站标题'),
        ),
    ]
