# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-13 19:32
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('zl955', '0002_auto_20181113_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guanggao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='请输入小于100字符的描述！', max_length=150, verbose_name='广告名字')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='zl955/abb/', verbose_name='广告图片')),
                ('href', models.CharField(help_text='请输入小于200字符的描述！', max_length=250, verbose_name='广告链接')),
                ('is_show', models.BooleanField(choices=[(True, '显示'), (False, '不显示')], default=True, max_length=2, verbose_name='是否显示')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '广告设置',
                'verbose_name_plural': '广告设置',
            },
        ),
        migrations.AlterField(
            model_name='settings',
            name='b_desc',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='底部显示信息'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='m_desc',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='中间显示信息'),
        ),
    ]
