# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-13 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zl955', '0003_auto_20181113_1932'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guanggao',
            new_name='Guanggaos',
        ),
    ]
