# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-24 19:42
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='users/avatar/default.png', null=True, upload_to='users/avatar/%Y/%m'),
        ),
    ]
