# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-19 12:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pk10_Open',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.IntegerField(unique=True, verbose_name='期号')),
                ('day_id', models.IntegerField(unique=True, verbose_name='当日期号')),
                ('opens', models.CharField(help_text='如需修改,请用逗号,间隔！', max_length=50, verbose_name='开奖号')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': 'PK10-开奖号',
                'verbose_name_plural': 'PK10-开奖号',
            },
        ),
    ]
