# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-20 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pk10', '0002_auto_20181119_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='pk10_open',
            name='_gyh',
            field=models.CharField(default=1, help_text='如需修改,请用逗号,间隔！', max_length=50, verbose_name='冠亚和'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pk10_open',
            name='_lh',
            field=models.CharField(default=1, help_text='如需修改,请用逗号,间隔！', max_length=50, verbose_name='1-5龙虎'),
            preserve_default=False,
        ),
    ]
