# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-20 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pk10', '0003_auto_20181120_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pk10_open',
            old_name='_gyh',
            new_name='gyh',
        ),
        migrations.RenameField(
            model_name='pk10_open',
            old_name='_lh',
            new_name='lh',
        ),
    ]
