# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-27 21:11
from __future__ import unicode_literals

import chat.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgs', models.TextField(default='', verbose_name='聊天消息')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '聊天信息',
                'verbose_name_plural': '聊天信息',
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='请输入小于15字符的描述！', max_length=20, verbose_name='聊天室名')),
                ('online', models.CharField(default='0', max_length=100, verbose_name='在线人数')),
                ('url', models.CharField(default=chat.models.randomURL, max_length=20, verbose_name='聊天地址')),
                ('avatar', imagekit.models.fields.ProcessedImageField(blank=True, default='chat/room/avatar/default.png', null=True, upload_to='chat/room/avatar/%Y/%m')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '聊天室',
                'verbose_name_plural': '聊天室',
            },
        ),
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.ChatRoom', verbose_name='房间名')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
            options={
                'verbose_name': ' 在线会员',
                'verbose_name_plural': ' 在线会员',
            },
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together=set([('url',)]),
        ),
        migrations.AddField(
            model_name='chatmsg',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.ChatRoom', verbose_name='房间名'),
        ),
        migrations.AddField(
            model_name='chatmsg',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
    ]
