# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-29 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20181127_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='online',
        ),
    ]
