# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-29 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_chatroom_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmsg',
            name='room',
        ),
        migrations.RemoveField(
            model_name='chatmsg',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatMsg',
        ),
    ]
